config/routes.rb
RailsBoard::Application.routes.draw do
    #REST-style URI
    resources :my_rails_board_rows

    root :to => 'my_rails_board_rows#index'

    match '/listSpecificPageWork',  to: 'my_rails_board_rows#listSpecificPageWork'    
    match '/searchWithSubject',  to: 'my_rails_board_rows#searchWithSubject'        
    match '/EditAdditionalParams',  to: 'my_rails_board_rows#EditAdditionalParams'       
end

app/models/my_rails_board_row.rb
# 모델은 단수로..
class MyRailsBoardRow < ActiveRecord::Base
    attr_accessible :hits, :mail, :memo, :name, :subject

    # 20120831
    before_save { |rowData| rowData.mail = mail.downcase }

    validates :name,  presence: true, length: { maximum: 50 }
    validates :subject,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :mail, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :memo,  presence: true, length: { maximum: 200 }
end

app/controllers/my_rails_board_rows_controller.rb
class MyRailsBoardRowsController < ApplicationController
    include ApplicationHelper

    #RESTful

    # --------------------------------------------------------------------------------------------------
    # HTTP request  URI                           Action      Purpose
    # --------------------------------------------------------------------------------------------------
    # GET           /my_rails_board_rows          index       page to list all my_rails_board_rows
    # GET           /my_rails_board_rows/1        show        page to show my_rails_board_rows with id 1
    # GET           /my_rails_board_rows/new      new         page to make a new my_rails_board_rows
    # POST          /my_rails_board_rows          create      create a new my_rails_board_rows
    # GET           /my_rails_board_rows/1/edit   edit        page to edit my_rails_board_rows with id 1
    # PUT           /my_rails_board_rows/1        update      update my_rails_board_rows with id 1
    # DELETE        /my_rails_board_rows/1        destroy     delete my_rails_board_rows with id 1


    # <a href="/static_pages/about">About</a>
    # but that isn’t the Rails Way. For one, it would be nice if the URI for the about page were 
    # /about rather than /static_pages/about; moreover, Rails conventionally uses named routes, which involves code like
    # <%= link_to "About", about_path %>

    #--------------------------------------------------------------------------#
    def index

        # url = '/listSpecificPageWork?current_page=1&searchStr=None'
        # Rails.logger.debug "!!! index url: #{url}"     
        # redirect_to url       
        
        # 좀더 RESTful 
        @searchStr = 'None'
        @current_page = '1'
        @totalCnt = MyRailsBoardRow.all.count                  
        @totalPageList = getTotalPageList( @totalCnt, rowsPerPage)        
        @boardList = 
                MyRailsBoardRow.find_by_sql ["select ID,SUBJECT,NAME, CREATED_AT, MAIL,MEMO,HITS \
                    from MY_RAILS_BOARD_ROWS ORDER BY id desc limit %s offset 0", rowsPerPage ] 

        render 'listSpecificPageWork'
    end
    #--------------------------------------------------------------------------#
    def show
        # 내용보기
        @id = params[:id]
        @current_page = params[:current_page] 
        @searchStr= params[:searchStr] 
                
        # hits increase        
        MyRailsBoardRow.increment_counter(:hits, @id  )

        @rowData = MyRailsBoardRow.find(params[:id])      

        render 'viewWork'  
    end
    #--------------------------------------------------------------------------#
    def new
        # 새로운 게시물 생성, 명시적으로 view를 지정한다. (기본적으로 new.html.erb를 참조함)
        @rowData = MyRailsBoardRow.new 
        render 'show_write_form'
    end
    
    #--------------------------------------------------------------------------#
    def create
        # 글쓰기 등록
        # params.each do |key,value|
        #    Rails.logger.warn "Param #{key}: #{value}"
        # end
        # Parameters: {"utf8"=>"✓", "authenticity_token"=>"TZ80O75xu52E0S3MXA49uTEkOdDMJE38INMRDIuVZOU=", "my_rails_board_row"=>{"name"=>"ggg", "mail"=>"ggg", "subject"=>"ggg", "memo"=>"ggg"}, "commit"=>"등록"}

        @rowData = MyRailsBoardRow.new(params[:my_rails_board_row])
                
        if @rowData.save          
          redirect_to '/'
        else
          render 'show_write_form'
        end
    end
    
    #--------------------------------------------------------------------------#    
    # def edit
        # 내용 수정을 위해 내용 출력하기. EditAdditionalParams 를 대신 사용함.
        # @id = params[:id]
        # @current_page = params[:current_page]
        # @searchStr = params[:searchStr] 

        # Rails.logger.debug @id
        # Rails.logger.debug @current_page
        # Rails.logger.debug @searchStr

        # @rowData = MyRailsBoardRow.find(params[:id])
        # render 'update'
    # end

    #--------------------------------------------------------------------------#
    def update
        # 변경내용을 저장할때
        @id = params[:id]
        @current_page = params[:current_page]
        @searchStr = params[:searchStr] 
        
        # Update DataBase
        @rowData = MyRailsBoardRow.find(params[:id])      

        if @rowData.update_attributes(params[:my_rails_board_row])
            # Display Page => POST 요청은 redirection!
            url = '/listSpecificPageWork?current_page=' + @current_page+'&searchStr='+@searchStr
            redirect_to url     
        else
            render 'update'
        end        
    end
    #--------------------------------------------------------------------------#
    def destroy

        Rails.logger.debug "current_page: #{params[:current_page]}"     

        MyRailsBoardRow.find(params[:id]).destroy
        
        # 차이점        
        # my_rails_board_rows_path => '/my_rails_board_rows'
        # my_rails_board_rows_url  => 'http://localhost:3000/my_rails_board_rows' => full URI

        # redirect_to my_rails_board_rows_url
        redirect_to my_rails_board_rows_path
    end    
    #--------------------------------------------------------------------------#           
    def EditAdditionalParams                
        @id = params[:id]
        @current_page = params[:current_page]
        @searchStr = params[:searchStr] 
        Rails.logger.debug @id
        Rails.logger.debug @current_page
        Rails.logger.debug @searchStr
        
        @rowData = MyRailsBoardRow.find(params[:id])
        render 'update'
    end    
    #--------------------------------------------------------------------------#
    def searchWithSubject
        
        @searchStr = params[:searchStr]
                        
        url = '/listSpecificPageWork?searchStr=' + @searchStr +'&current_page=1'
        Rails.logger.debug "***** url:" + url
        
        uri = URI.encode(url.strip)         
        Rails.logger.debug uri
        
        redirect_to uri
    end    
    #--------------------------------------------------------------------------#
    def listSpecificPageWork
        @current_page = params[:current_page]      
        @searchStr = URI.decode(params[:searchStr])   
        
        Rails.logger.debug "listSpecificPageWork: @searchStr=" + @searchStr
        Rails.logger.debug "!!! searchStr: #{@searchStr}"     
        
        # 페이지를 가지고 범위 데이터를 조회한다 => raw SQL 사용함
        # @boardList = MyRailsBoardRow.find_by_sql ["SELECT Z.* FROM(SELECT X.*, ceil( rownum / %s ) \ 
        #     as page FROM ( SELECT ID,SUBJECT,NAME, CREATED_AT, MAIL,MEMO,HITS \
        #         FROM MY_RAILS_BOARD_ROWS  ORDER BY ID DESC ) X ) Z WHERE page = %s", rowsPerPage, @current_page]  
                
        if @searchStr == 'None'
            @totalCnt = MyRailsBoardRow.all.count                  
            @totalPageList = getTotalPageList( @totalCnt, rowsPerPage)
            #sqlite3         
            @boardList = 
                MyRailsBoardRow.find_by_sql ["select ID,SUBJECT,NAME, CREATED_AT, MAIL,MEMO,HITS \
                    from MY_RAILS_BOARD_ROWS ORDER BY id desc limit %s offset %s", 
                    rowsPerPage, @current_page.to_i ==1 ? 0 : 2*(@current_page.to_i-1) ] 
        else
            # 검색처리
            @totalCnt = MyRailsBoardRow.where("subject LIKE ?","%#{@searchStr}%").count() 
            @totalPageList = getTotalPageList( @totalCnt, rowsPerPage)
            @boardList = 
                MyRailsBoardRow.find_by_sql [
            "select ID,SUBJECT,NAME, CREATED_AT, MAIL,MEMO,HITS from MY_RAILS_BOARD_ROWS where subject like '%%%s%%' ORDER BY id desc
             limit %s offset %s", @searchStr,rowsPerPage, @current_page.to_i ==1 ? 0 : 2*(@current_page.to_i-1) ] 
         end
    end
end

app/helpers/my_rails_board_rows_helper.rb
module MyRailsBoardRowsHelper
end

app/views/my_rails_board_rows/_rowDataInput.html.erb
    <tr>
        <td><b><%= f.label :name %></b></td>
        <% if @readOnlyFlag == 1 %>
            <td><%= f.text_field :name,:readonly => true %><br /></td>
        <% else %>
            <td><%= f.text_field :name %><br /></td>            
        <% end %>
    </tr>
    <tr>
        <td><b><%= f.label :mail %></b></td>
        <% if @readOnlyFlag == 1 %>
            <td><%= f.text_field :mail,:readonly => true %><br /></td>
        <% else %>
            <td><%= f.text_field :mail %><br /></td>            
        <% end %>        
    </tr>
    <tr>
        <td><b><%= f.label :subject %></b></td>
        <% if @readOnlyFlag == 1 %>
            <td><%= f.text_field :subject,:readonly => true %><br /></td>
        <% else %>
            <td><%= f.text_field :subject %><br /></td>            
        <% end %>        
    </tr>
    <tr>
        <td><b><%= f.label :memo %></b></td>
        <% if @readOnlyFlag == 1 %>
            <td><%= f.text_area :memo,:readonly => true %><br /></td>
        <% else %>
            <td><%= f.text_area :memo %><br /></td>            
        <% end %>        
    </tr>

app/views/my_rails_board_rows/listSpecificPageWork.html.erb
<table cellspacing=1 width=700 border=0>
    <tr>
        <td>총 게시물수: <%=@totalCnt%></td>
        <td><p align=right> 페이지:<%=@current_page%></td>        
    </tr>
</table>

<table cellspacing=1 width=700 border=1>
    <tr>
        <td width=50><p align=center>번호</p></td>
        <td width=100><p align=center>이름</p></td>
        <td width=320><p align=center>제목</p></td>
        <td width=100><p align=center>등록일</p></td>
        <td width=100><p align=center>조회수</p></td>
    </tr>
    
    <% if @boardList.any? %>
        <ul>            
            <%  @boardList.each do |boardRow| %>
            <tr>
            <td width=50><p align=center><%=boardRow.id%></p></td>
            <td width=100><p align=center><%=boardRow.name%></p></td>                
            <td width=320>
                <p align=center>                    
                    <%= link_to boardRow.subject, my_rails_board_row_path(:id => boardRow.id, :current_page=>@current_page, :searchStr=>@searchStr), :method => :get %>
                </p>
            </td>                      
            <td width=100><p align=center><%=boardRow.created_at%></p></td>
            <td width=100><p align=center><%=boardRow.hits%></p></td>
            </tr>       
            <% end %>
        </ul>
    <% else %>
        <p>No Data.</p>
    <% end %>
</table>

<table cellspacing=1 width=700 border=1 >
    <tr>
        <td>      
        <%  @totalPageList.each do |page| %>
            <a href="/listSpecificPageWork?current_page=<%=page%>&searchStr=<%=@searchStr%>" >
            [
            <!-- Fixnum 과 String 을 비교하기 위해서 변환 -->
            <% if page == @current_page.to_i %>
                <b>
            <% end %>

            <%=page%>

            <% if page == @current_page.to_i %>
                </b>
            <% end %>
            ]
         <% end %>        
        </td>
    </tr>
</table>

<% if @searchStr == 'None' %>
    <form name="searchf" method="post" action="/searchWithSubject/"> 
    <table width=700>
        <tbody>
            <tr>
                <td valign="center">
                    <p align="left"><input class="btn btn-large btn-primary" value="글쓰기" onclick="window.location='/my_rails_board_rows/new'"  type="button"></p>
                </td>
                <td valign="right">
                    
                        <p align="right"><input name="searchStr" size="30" maxlength="50" type="text"></p>
                    
                </td>
                <td valign="center">
                    <p align="right"><input class="btn btn-large btn-primary" value="글찾기" type="submit"></p>
                </td>
            </tr>
        </tbody>
    </table>
    </form>
<% else %>
    <table width=700>
        <tr>
            <td><input type=button class="btn btn-large btn-primary" value="전체 목록으로 돌아가기"  OnClick="window.location='/'" >         
        </tr>
    </table>
<% end %>

app/views/my_rails_board_rows/show_write_form.html.erb
<% provide(:title, '게시판 글쓰기') %>

<table cellspacing = 0 cellpadding = 5 border = 1 width=500>

    <%= form_for(@rowData) do |f| %>    
        <%= render 'shared/error_messages' %>     
        
        <% @readOnlyFlag = 0 %>       
        <%= render :partial => "rowDataInput", :locals => { :f => f , :readOnlyFlag => @readOnlyFlag } %>                   

        <table width="150">
            <tr>
                <td>
                    <%= f.submit "등록", class: "btn btn-large btn-primary" %>
                </td>                
            </tr>
        </table>
    <% end %>
</table>

app/views/my_rails_board_rows/update.html.erb
<% provide(:title, '글 수정'+@rowData.name) %>

<table cellspacing = 0 cellpadding = 5 border = 1 width=500>

    <%= form_for(@rowData) do |f| %>        
        <input type=hidden name=id  value="<%=@id%>">    
        <input type=hidden name=current_page  value="<%=@current_page%>">
        <input type=hidden name=searchStr  value="<%=@searchStr%>">

        <%= render 'shared/error_messages' %>  
        
        <!-- http://guides.rubyonrails.org/layouts_and_rendering.html -->
        <% @readOnlyFlag = 0 %>       
        <%= render :partial => "rowDataInput", :locals => { :f => f , :readOnlyFlag => @readOnlyFlag } %>

        <table width="150">
            <tr>                
                <td>
                    <%= f.submit "재등록", class: "btn btn-large btn-primary" %> 
                </td>
                
                <td>
                    <%= button_to  "목록", {:action => "listSpecificPageWork", :current_page => @current_page, :searchStr => @searchStr} ,class: "btn btn-large btn-primary" %>
                </td>        
            </tr>
        </table>
    
    <% end %>
</table>

app/views/my_rails_board_rows/viewWork.html.erb
<% provide(:title, '글보기'+@rowData.name) %>

<table cellspacing = 0 cellpadding = 5 border = 1 width=500>

    <%= form_for(@rowData) do |f| %>                    
        <% @readOnlyFlag = 1 %>       
        <%= render :partial => "rowDataInput", :locals => { :f => f , :readOnlyFlag => @readOnlyFlag } %>
            
    <% end %>    
</table>

<table width="150">
    <tr>
        <td><%= button_to '수정' , {:action => "EditAdditionalParams", :id => @id, :current_page => @current_page, :searchStr => @searchStr} ,class: "btn btn-large btn-primary" %></td>
                
        <td><%= button_to  "삭제", my_rails_board_row_path(:id => @id, :current_page => @current_page, :searchStr => @searchStr),class: "btn btn-large btn-primary", :confirm => 'Are you sure?', :method=> :delete %>
        </td>
        
        <td><%= button_to '목록' , {:action => "listSpecificPageWork", :current_page => @current_page, :searchStr => @searchStr} ,class: "btn btn-large btn-primary" %></td>
    </tr>
</table> 